replicaCount: 1

## Create the provided Roles and RoleBindings
##
role:
  create: true

## Create the provided ClusterRoles and ClusterRoleBindings
##
clusterRole:
  create: true

nodeSelector:
  node: system

manager:
  image:
    repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
  collectorImage:
    repository:  otel/opentelemetry-collector-contrib #ghcr.io/wjma90/otelcol-distributions/opentelemetry-collector-main-k8s # otel/opentelemetry-collector-contrib
    # tag: 1.1.0
  serviceMonitor:
    enabled: false

#kubeRBACProxy:
#  enabled: true
#  image:
#    repository: quay.io/brancz/kube-rbac-proxy

admissionWebhooks:
  pods:
    failurePolicy: Ignore #Fail #Ignore
  namespaceSelector:
    matchExpressions:
       - key: kubernetes.io/metadata.name
         operator: NotIn
         values:
         - kube-system
         - o11y
         - istio-operator
         - istio-system